### PR TITLE
Overhaul and simplify RequestAuthorizer's concurrency model

### PR DESCRIPTION
**Pull request by sharplet**
This test runs somewhat slowly on CI, so the timeout is increased to 3 seconds to reduce intermittent test failures.

### CODE REVIEW

**Comment by sharplet** [comment]
🤔 

Is there a real race condition here? Maybe I'll try an enormous timeout and rerun CI a few times.

**Comment by sharplet** [comment]
....yep looks like a problem:

```
SuperbTests.RequestAuthorizerSpec
  notifies_multiple_pending_requests_of_authentication_failure, expected to eventually equal <50>, got <31>
  /Users/distiller/Superb/Tests/SuperbTests/RequestAuthorizerSpec.swift:148
  ```
      requests.verify()
      expect(errors.count).toEventually(equal(limit), timeout: 30)
      expect(allCancelled).to(beTrue())
  ```


	 Executed 17 tests, with 1 failure (0 unexpected) in 30.941 (30.949) seconds
```

**Comment by sharplet** [comment]
This is ready for review again.

**What was the problem?**

While investigating the race condition in the tests, I was able to determine that `RequestAuthorizer` is still thread-safe, but it was actually the test itself that had the race condition. Here is where the problem occurred:

```swift
      let examples = (1...5000).map { "/example\($0)" }
      examples.forEach { _ in group.enter() } // (1)

      DispatchQueue.concurrentPerform(iterations: examples.count) { i in
        let example = examples[i]
        let request = testRequest(path: example)

        authorizer.performAuthorized(request) { result in
          DispatchQueue.main.async {
            completedRequests.insert(example)
            if let error = result.error {
              errors.append(error)
            }
          }
        }

        // (2)
        group.leave()
      }

      group.wait()

      // (3)
      testProvider.complete(with: .cancelled)
```

At point (1) we set up a `DispatchGroup`, whose purpose is to allow us to wait for all the pending requests to be enqueued before completing authentication at (3). Implicitly assumed here is that whenever we hit (2), the request that was performed is completely enqueued and waiting for authentication to complete. **It turns out that was false!** Because the internal call to `performAuthorized(_:reauthenticate:completionHandler:)` was dispatched onto a global concurrent queue, it's possible for the dispatch group to complete before all of those globally scheduled blocks have completed.

The simple workaround (in ec55052) was to remove the unnecessary queue shift and enqueue the request as quickly as possible. Too much concurrency is not a good thing.

**What else changed?**

All this investigation made me realise that a couple of the internal abstractions used by `RequestAuthorizer` were unnecessary, and probably making things much _slower_ than they needed to be. To that end, the explicit `Actor` and `Channel` classes are no more, and `RequestAuthorizer` now explicitly manages an internal queue of pending requests as a plain old array.

How is this better? Well, `RequestAuthorizer` is still actually modelled as an actor: it has private state that it only manages on a private, serial `messageQueue`. We no longer use `DispatchQueue.sync`, favouring `DispatchQueue.async`, and explicitly dispatch completion handlers onto a configuration `completionQueue`.

I believe that removing these blocking and synchronisation based primitives should _increase_ performance by allowing GCD to minimise context switches and spawn fewer threads to meet the same workload.

**Comment by sharplet** [comment]
> I believe that removing these blocking and synchronisation based primitives should increase performance by allowing GCD to minimise context switches and spawn fewer threads to meet the same workload.

Oh, and to that end, I was able to increase the number of requests from 50 to 5000 in the aforementioned failing test, and it still completes super quick :)

**Comment by nashfive** [comment]
Awesome overhaul! RequestAuthorizer looks more approachable now. Thanks for this!

**Pull request merged**
